name: vplot
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9,<3.15
  - numpy>=2.0.0
  - pip
  - scipy
  - setuptools
  - pandoc
  - ipykernel
  - nb_conda
  - nb_conda_kernels
  - nb_anacondacloud
  - pip:
    - astropy>=6.1.0
    - matplotlib>=3.9.0
    - pytest>=8.0.0
    - pytest-cov>=4.1.0
    - pytest-timeout>=2.1.0
    - sphinx>=8.0.0
    - jupyter_client
    - nbconvert
    - nbsphinx
