name: vplot
channels:
  - defaults
dependencies:
  - python=3.7.3
  - numpy>=1.19.2
  - pip>=20.3.3
  - scipy>=1.5.2
  - setuptools>=51.3.3
  - pip:
    - matplotlib>=3.3.3
    - nose>=1.3.7
    - parameterized>=0.8.1
    - pytest>=6.2.4
    - pytest-dependency>=0.5.1
    - pytest-env>=0.6.2
    - pytest-cov>=2.11.1
    - sphinx>=4.0.1
    - git+https://github.com/VirtualPlanetaryLaboratory/vplanet-private.git@pip # TODO! Remove this in production