trigger:
  - dev
  - master

jobs:
- job: Default
  timeoutInMinutes: 60
  pool:
    vmImage: Ubuntu-16.04
  steps:

  - bash: .ci/setup.sh
    displayName: 'Setup'

  - bash: .ci/run_tests.sh
    displayName: 'Run tests'
    env:
      BUILDREASON: $(Build.Reason)
      GHUSER: $(GITHUB_USER)
      GHKEY: $(GITHUB_API_KEY)

  - bash: .ci/build_docs.sh
    displayName: 'Build docs'
    env:
      BUILDREASON: $(Build.Reason)
      GHUSER: $(GITHUB_USER)
      GHKEY: $(GITHUB_API_KEY)
      GHBRANCH: $(Build.SourceBranchName)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results'
