name: tests

on:
  push:

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup_python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vplot
          environment-file: environment.yml

      - uses: actions/checkout@v2
        with:
          repository: VirtualPlanetaryLaboratory/vplanet-private
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: pip
          path: vplanet

      - name: Install vplanet
        id: install_vplanet
        if: steps.setup_python.outcome == 'success'
        working-directory: vplanet
        shell: bash -l {0}
        run: |
          python -m pip install .
          python -m pip uninstall -y vplot

      - name: Install vplot
        id: install_vplot
        if: steps.install_vplanet.outcome == 'success'
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install .

      - name: Run tests
        if: steps.install_vplot.outcome == 'success'
        shell: bash -l {0}
        run: python -m pytest -v tests --junitxml=junit/test-results.xml

      - name: Get unique id
        id: unique-id
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: |
          export JOB_ID=`echo $STRATEGY_CONTEXT | md5sum`
          echo "::set-output name=id::$JOB_ID"

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit/test-*.xml
          comment_mode: update last